### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fire' of undefined

### ISSUE THREAD

**Issue by scorsi** [kaisermann/svelte-page#3]
Hi,

I'm running the given example (and changing "../../Router.html" to "svelte-page/Router.html") and I got the following error. It seems that the "Router" component didn't have a "Store" attribute.

```
Uncaught TypeError: Cannot read property 'fire' of undefined
    at ctx (helpers.js:84)
    at page.mjs:1142
    at nextEnter (page.mjs:705)
    at page.mjs:1143
    at nextEnter (page.mjs:705)
    at helpers.js:61
    at page.mjs:1142
    at nextEnter (page.mjs:705)
    at _pageInstance (Router.html:47)
    at page.mjs:1142
```

Do you know where this error could come from ?

Thanks,

**Comment by kaisermann** [comment]
Oops, my bad! Fixed on `2.0.3` 😁
